import type { Slide, SlideElement } from "../../lib/types";
import { googleFontOptions } from "./fontOptions";

export type CarouselSlideTemplate = {
  id: string;
  name: string;
  description: string;
  elements: SlideElement[];
  background?: Slide["background"];
};

const baseFont = googleFontOptions[0].stack;
const accentFont = googleFontOptions[7].stack;
const serifFont = googleFontOptions[9].stack;

export const carouselSlideTemplates: CarouselSlideTemplate[] = [
  {
    id: "cover",
    name: "Cover",
    description: "Big title with a compact supporting line.",
    elements: [
      {
        id: "template-cover-kicker",
        type: "text",
        x: 0.12,
        y: 0.14,
        width: 0.5,
        height: 0.08,
        content: "01 / GUIDE",
        style: {
          fontFamily: baseFont,
          fontSize: 22,
          fontWeight: 700,
          color: "#e7ece5",
          textAlign: "left",
          lineHeight: 1,
        },
      },
      {
        id: "template-cover-title",
        type: "text",
        x: 0.12,
        y: 0.5,
        width: 0.76,
        height: 0.24,
        content: "Launch checklist",
        style: {
          fontFamily: baseFont,
          fontSize: 56,
          fontWeight: 800,
          color: "#ffffff",
          textAlign: "left",
          lineHeight: 0.96,
        },
      },
      {
        id: "template-cover-caption",
        type: "text",
        x: 0.12,
        y: 0.78,
        width: 0.68,
        height: 0.1,
        content: "A focused carousel for practical steps and examples.",
        style: {
          fontFamily: baseFont,
          fontSize: 24,
          fontWeight: 600,
          color: "#d7ded3",
          textAlign: "left",
          lineHeight: 1.12,
        },
      },
    ],
  },
  {
    id: "real-depth",
    name: "Real Depth",
    description: "Editorial text slide with deep contrast and long-form body copy.",
    background: {
      type: "solid",
      color: "#000000",
      overlayOpacity: 0.72,
    },
    elements: [
      {
        id: "template-real-depth-step",
        type: "text",
        x: 0.1,
        y: 0.25,
        width: 0.55,
        height: 0.06,
        content: "07 / 08 - REAL DEPTH",
        style: {
          fontFamily: accentFont,
          fontSize: 22,
          fontWeight: 800,
          color: "#8f8f96",
          textAlign: "left",
          lineHeight: 1,
          letterSpacing: 1.8,
          textTransform: "uppercase",
        },
      },
      {
        id: "template-real-depth-title",
        type: "text",
        x: 0.1,
        y: 0.34,
        width: 0.82,
        height: 0.12,
        content: "A warm-up for creative limits.",
        style: {
          fontFamily: accentFont,
          fontSize: 54,
          fontWeight: 800,
          color: "#ffffff",
          textAlign: "left",
          lineHeight: 0.96,
        },
      },
      {
        id: "template-real-depth-body",
        type: "text",
        x: 0.1,
        y: 0.46,
        width: 0.82,
        height: 0.32,
        content:
          "Use this space for a clear reflective paragraph. Keep the rhythm calm, let the main idea breathe, and make one sentence carry the deeper point of the slide.",
        style: {
          fontFamily: baseFont,
          fontSize: 29,
          fontWeight: 500,
          color: "#b7b7bc",
          textAlign: "left",
          lineHeight: 1.38,
        },
      },
      {
        id: "template-real-depth-next",
        type: "text",
        x: 0.1,
        y: 0.88,
        width: 0.32,
        height: 0.05,
        content: "NEXT ... ->",
        style: {
          fontFamily: accentFont,
          fontSize: 21,
          fontWeight: 800,
          color: "#f2f2f2",
          textAlign: "left",
          lineHeight: 1,
          letterSpacing: 2,
          textTransform: "uppercase",
        },
      },
      {
        id: "template-real-depth-count",
        type: "text",
        x: 0.82,
        y: 0.05,
        width: 0.12,
        height: 0.06,
        content: "7/8",
        style: {
          fontFamily: accentFont,
          fontSize: 30,
          fontWeight: 700,
          color: "#f4f4f4",
          textAlign: "right",
          lineHeight: 1,
        },
      },
    ],
  },
  {
    id: "checklist",
    name: "Checklist",
    description: "Stacked action list for educational posts.",
    elements: [
      {
        id: "template-checklist-title",
        type: "text",
        x: 0.1,
        y: 0.12,
        width: 0.8,
        height: 0.12,
        content: "Before you publish",
        style: {
          fontFamily: accentFont,
          fontSize: 44,
          fontWeight: 800,
          color: "#ffffff",
          textAlign: "left",
          lineHeight: 1,
        },
      },
      {
        id: "template-checklist-items",
        type: "text",
        x: 0.12,
        y: 0.35,
        width: 0.76,
        height: 0.36,
        content: "1. Define the promise\n2. Keep one idea per slide\n3. Check the export preview",
        style: {
          fontFamily: baseFont,
          fontSize: 30,
          fontWeight: 700,
          color: "#f4f7f1",
          textAlign: "left",
          lineHeight: 1.28,
        },
      },
      {
        id: "template-checklist-footer",
        type: "text",
        x: 0.12,
        y: 0.82,
        width: 0.62,
        height: 0.08,
        content: "Save this for the next carousel",
        style: {
          fontFamily: baseFont,
          fontSize: 22,
          fontWeight: 600,
          color: "#d7ded3",
          textAlign: "left",
          lineHeight: 1,
        },
      },
    ],
  },
  {
    id: "quote",
    name: "Quote",
    description: "Centered quote with author or context line.",
    elements: [
      {
        id: "template-quote-mark",
        type: "text",
        x: 0.12,
        y: 0.18,
        width: 0.76,
        height: 0.1,
        content: "\"",
        style: {
          fontFamily: serifFont,
          fontSize: 74,
          fontWeight: 800,
          color: "#e7ece5",
          textAlign: "center",
          lineHeight: 0.8,
        },
      },
      {
        id: "template-quote-body",
        type: "text",
        x: 0.12,
        y: 0.34,
        width: 0.76,
        height: 0.28,
        content: "Strong carousels are built slide by slide, not decoration by decoration.",
        style: {
          fontFamily: serifFont,
          fontSize: 36,
          fontWeight: 800,
          color: "#ffffff",
          textAlign: "center",
          lineHeight: 1.08,
        },
      },
      {
        id: "template-quote-source",
        type: "text",
        x: 0.22,
        y: 0.72,
        width: 0.56,
        height: 0.08,
        content: "InstaSetka note",
        style: {
          fontFamily: baseFont,
          fontSize: 22,
          fontWeight: 600,
          color: "#d7ded3",
          textAlign: "center",
          lineHeight: 1,
        },
      },
    ],
  },
];
